- name: Pull frontend image
  community.docker.docker_image:
    name: "{{ frontend_image }}"
    tag: "{{ dockerhub_tag }}"
    source: pull

- name: Run frontend container
  community.docker.docker_container:
    name: frontend
    image: "test:{{ dockerhub_tag }}"
    state: started
    restart_policy: always
    ports: "{{ frontend_ports }}"
    networks:
      - name: pokecrawler_network
        aliases:
          - frontend
    networks_cli_compatible: true
