- name: Add ngrok GPG key
  apt_key:
    url: https://ngrok-agent.s3.amazonaws.com/ngrok.asc
    state: present

- name: Add ngrok repository
  apt_repository:
    repo: 'deb https://ngrok-agent.s3.amazonaws.com buster main'
    state: present
    filename: 'ngrok'

- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install ngrok
  apt:
    name: ngrok
    state: present

- name: Check if ngrok is installed
  command: ngrok version
  register: ngrok_installed
  ignore_errors: yes

- name: Add ngrok authtoken
  command: ngrok config add-authtoken {{ ngrok_auth_token }}
  when: ngrok_installed.stdout != ''  # Verifica se o ngrok está instalado

- name: Start ngrok tunnel
  ansible.builtin.shell: "nohup ngrok http --url=humane-sharp-teal.ngrok-free.app 8080 > /dev/null 2>&1 &"
  async: 3600
  poll: 0
  register: ngrok_process

