- name: Add ngrok GPG key
  ansible.builtin.shell: |
    curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc | tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
  args:
    warn: false

- name: Add ngrok APT repository
  ansible.builtin.shell: |
    echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | tee /etc/apt/sources.list.d/ngrok.list
  args:
    warn: false

- name: Update APT cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install ngrok
  ansible.builtin.apt:
    name: ngrok
    state: present

- name: Add ngrok authtoken
  ansible.builtin.shell: "ngrok config add-authtoken {{ ngrok_authtoken }}"
  environment:
    HOME: "/home/{{ ansible_user }}"  # Diretório home do usuário que executa o Ansible

- name: Run ngrok tunnel in background
  ansible.builtin.shell: "nohup ngrok http --domain={{ ngrok_domain }} 8080 > /var/log/ngrok.log 2>&1 &"
  args:
    warn: false
