- name: Pull Postgres image
  community.docker.docker_image:
    name: "{{ database_image }}"
    tag: "{{ dockerhub_tag }}"
    source: pull

- name: Run Postgres container
  community.docker.docker_container:
    name: postgres
    image: "{{ database_image }}"
    state: started
    restart_policy: always
    ports: "{{ database_ports }}"
    env: "{{ database_env }}"
    volumes:
          - "{{ role_path }}/files/init.sql:/docker-entrypoint-initdb.d/init.sql:ro"
    networks:
      - name: pokecrawler_network
        aliases:
          - postgres
    networks_cli_compatible: true
