#dockerhub_user: a2009076370
dockerhub_user: flmoreira
dockerhub_tag: latest

database_host: postgres
database_port: "5432"
database_env:
  POSTGRES_DB: pokecrawlerdb
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password

frontend_host: "localhost"
frontend_port: "3000"

backend_host: "localhost"
backend_port: "8000"

keycloak_host: "localhost"
keycloak_port: "8180"

jenkins_port: 8080
