services:
  backend:
    build: ./backend
    image: a2009076370/backend:latest
    ports:
      - "8000:8000"
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: pokedb

  crawler:
    build: ./crawler
    image: a2009076370/crawler:latest

  frontend:
    build: ./frontend
    image: a2009076370/frontend:latest
    ports:
      - "3000:3000"

    #volumes:
      #- ./frontend:/app  # Isto permite alterações sem rebuild
      #- /app/node_modules  # Evita problemas de dependências
    #environment:
        #- CHOKIDAR_USEPOLLING=true  # Para hot reload funcionar dentro do Docker
      
      
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pokedb
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: keycloak/keycloak:26.1.4
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - "8080:8080"

volumes:
  postgres_data:
