services:
  backend:
    build: ./backend
    image: a2009076370/backend:latest
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - keycloak
      - db
    environment:
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=pokedb
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=pokecrawler
      - KEYCLOAK_CLIENT_ID=backend-client
      - KEYCLOAK_CLIENT_SECRET=YMk0vq10Ne4KFhcSGOqgQMZWV1Jw7hdb

  crawler:
    build: ./crawler
    image: a2009076370/crawler:latest
    container_name: crawler

  frontend:
    build: ./frontend
    image: a2009076370/frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pokedb
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: keycloak/keycloak:26.1.4
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8180:8080"
    command: start-dev
    volumes:
      - keycloak_data:/opt/keycloak/data

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  postgres_data:
  keycloak_data:
  jenkins_home:
    external: true
    name: jenkins_home
