- name: Run Keycloak container
  community.docker.docker_container:
    name: keycloak
    image: "{{ keycloak_image }}"
    state: started
    restart_policy: always
    ports: "{{ keycloak_ports }}"
    env: "{{ keycloak_env }}"
    command: start-dev
    networks:
      - name: pokecrawler_network
        aliases:
          - keycloak  # ou qualquer nome que o container do crawler vai usar para resolver a DB

    volumes:
          - "keycloak_data:/opt/keycloak/data"

- name: Definir Keycloak host and port if Jenkins or local
  set_fact:
    keycloak_host: "{{ 'keycloak' if jenkins | default(false) else keycloak_host }}"
    keycloak_port: "{{ 8080 if jenkins | default(false) else keycloak_port }}"

- name: Esperar que o Keycloak esteja disponível
  wait_for:
    host: "{{ keycloak_host }}"
    port: "{{ keycloak_port }}"
    delay: 2
    timeout: 60
    state: started

- name: Create realm via Keycloak REST API
  uri:
    url: "http://{{ keycloak_host }}:{{ keycloak_port }}/realms/master/protocol/openid-connect/token"
    method: POST
    body:
      grant_type: password
      client_id: admin-cli
      username: admin
      password: admin
    body_format: form-urlencoded
    return_content: yes
  register: keycloak_token

- name: Create pokecrawler realm
  uri:
    url: "http://{{ keycloak_host }}:{{ keycloak_port }}/admin/realms"
    method: POST
    headers:
      Authorization: "Bearer {{ keycloak_token.json.access_token }}"
      Content-Type: "application/json"
    body: |
      {
        "realm": "pokecrawler",
        "enabled": true
      }
    status_code: 201

- name: Criar client "frontend-client" no realm "pokecrawler"
  uri:
    url: "http://{{ keycloak_host }}:{{ keycloak_port }}/admin/realms/pokecrawler/clients"
    method: POST
    headers:
      Authorization: "Bearer {{ keycloak_token.json.access_token }}"
      Content-Type: "application/json"
    body_format: json
    body:
      clientId: "frontend-client"
      enabled: true
      publicClient: true
      redirectUris:
        - "http://localhost:3000/*"
      webOrigins:
        - "http://localhost:3000"
      directAccessGrantsEnabled: true
      protocol: "openid-connect"
    status_code: 201

- name: Criar user "ash" no realm "pokecrawler"
  uri:
    url: "http://{{ keycloak_host }}:{{ keycloak_port }}/admin/realms/pokecrawler/users"
    method: POST
    headers:
      Authorization: "Bearer {{ keycloak_token.json.access_token }}"
      Content-Type: "application/json"
    body_format: json
    body:
      username: "ash"
      enabled: true
      emailVerified: true
      firstName: "Ash"
      lastName: "Ketchum"
      email: "ash@pokecrawler.com"
    status_code: 201

- name: Buscar user_id do "ash"
  uri:
    url: "http://{{ keycloak_host }}:{{ keycloak_port }}/admin/realms/pokecrawler/users?username=ash"
    method: GET
    headers:
      Authorization: "Bearer {{ keycloak_token.json.access_token }}"
    return_content: yes
  register: keycloak_users

- name: Definir password do user "ash"
  uri:
    url: "http://{{ keycloak_host }}:{{ keycloak_port }}/admin/realms/pokecrawler/users/{{ keycloak_users.json[0].id }}/reset-password"
    method: PUT
    headers:
      Authorization: "Bearer {{ keycloak_token.json.access_token }}"
      Content-Type: "application/json"
    body_format: json
    body:
      type: "password"
      temporary: false
      value: "pikachu123"
    status_code: 204

