- name: Gerar .env para o crawler
  copy:
    dest: /opt/pokecrawler/.env
    content: |
      POSTGRES_DB={{ database_env.POSTGRES_DB }}
      POSTGRES_USER={{ database_env.POSTGRES_USER }}
      POSTGRES_PASSWORD={{ database_env.POSTGRES_PASSWORD }}
      POSTGRES_HOST={{ database_host }}
      POSTGRES_PORT={{ database_port }}
    mode: '0640'

- name: Pull crawler image
  community.docker.docker_image:
    name: "{{ crawler_image }}"
    tag: "{{ dockerhub_tag }}"
    source: pull

- name: Run backend container
  community.docker.docker_container:
    name: crawler
    image: "{{ crawler_image }}:{{ dockerhub_tag }}"
    state: started
    restart_policy: always
    ports: "{{ crawler_ports }}"

