- name: Pull crawler image
  community.docker.docker_image:
    name: "{{ crawler_image }}"
    tag: "{{ dockerhub_tag }}"
    source: pull

- name: Run crawler container
  community.docker.docker_container:
    name: crawler
    image: "{{ crawler_image }}:{{ dockerhub_tag }}"
    ports: "{{ crawler_ports }}"
    env:
      POSTGRES_DB: "{{ database_env.POSTGRES_DB }}"
      POSTGRES_USER: "{{ database_env.POSTGRES_USER }}"
      POSTGRES_PASSWORD: "{{ database_env.POSTGRES_PASSWORD }}"
      POSTGRES_HOST: "{{ database_host }}"
      POSTGRES_PORT: "{{ database_port }}"
    networks:
      - name: pokecrawler_network
        aliases:
          - crawler  # ou qualquer nome que o container do crawler vai usar para resolver a DB
    networks_cli_compatible: true
