- name: Deploy PostgreSQL
  hosts: database
  become: true
  tasks:
    - name: Run PostgreSQL container
      community.docker.docker_container:
        name: postgres
        image: "{{ database_image }}"
        state: started
        restart_policy: always
        ports: "{{ database_ports }}"
        env: "{{ database_env }}"
