- name: Deploy Keycloak
  hosts: dev
  tasks:
    - name: Run Keycloak container
      community.docker.docker_container:
        name: keycloak
        image: "{{ keycloak_image }}"
        state: started
        restart_policy: always
        ports: "{{ keycloak_ports }}"
        env: "{{ keycloak_env }}"
