- name: Pull backend image
  community.docker.docker_image:
    name: "{{ backend_image }}"
    tag: "{{ dockerhub_tag }}"
    source: pull

- name: Run backend container
  community.docker.docker_container:
    name: backend
    image: "{{ backend_image }}:{{ dockerhub_tag }}"
    state: started
    restart_policy: always
    ports: "{{ backend_ports }}"
    env:
      POSTGRES_DB: "{{ database_env.POSTGRES_DB }}"
      POSTGRES_USER: "{{ database_env.POSTGRES_USER }}"
      POSTGRES_PASSWORD: "{{ database_env.POSTGRES_PASSWORD }}"
      POSTGRES_HOST: "{{ database_host }}"
      POSTGRES_PORT: "{{ database_port }}"
    networks:
      - name: pokecrawler_network
        aliases:
          - backend  # ou qualquer nome que o container do crawler vai usar para resolver a DB
    networks_cli_compatible: true

