- name: Deploy Pokecrawler AI
  hosts: all
  become: yes
  tasks:
    
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
      tags:
        - docker
    
    - name: Start Services
      command: docker-compose up -d
      tags:
         - deploy

    - name: Adicionar cron manualmente no /etc/crontab
      lineinfile:
        path: "/etc/crontab"
        line: "0 * * * * root cd /home/fab/pd/project/pokecrawler-ai && /usr/bin/docker compose up -d crawler >> /var/log/pokecrawler_crawler.log.$(date +\\%Y\\%m\\%d) 2>&1"
        create: yes
      tags:
        - cron
