- name: Deploy pokecrawler stack
  hosts: meus-servidores
  become: true

  vars_files:
    - vars/backend.yml
    - vars/frontend.yml
    - vars/crawler.yml

  tasks:

    - name: Instalar Docker (Debian)
      apt:
        name: docker.io
        state: present
      when: ansible_os_family == 'Debian'

    - name: Garantir que Docker está ativo
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull backend image
      community.docker.docker_image:
        name: "{{ backend_image }}"
        tag: "{{ backend_tag }}"
        source: pull

    - name: Run backend container
      community.docker.docker_container:
        name: backend
        image: "{{ backend_image }}:{{ backend_tag }}"
        state: started
        restart_policy: always
        ports: "{{ backend_ports }}"

    - name: Pull frontend image
      community.docker.docker_image:
        name: "{{ frontend_image }}"
        tag: "{{ frontend_tag }}"
        source: pull

    - name: Run frontend container
      community.docker.docker_container:
        name: frontend
        image: "{{ frontend_image }}:{{ frontend_tag }}"
        state: started
        restart_policy: always
        ports: "{{ frontend_ports }}"

    - name: Pull crawler image
      community.docker.docker_image:
        name: "{{ crawler_image }}"
        tag: "{{ crawler_tag }}"
        source: pull

    - name: Run crawler container
      community.docker.docker_container:
        name: crawler
        image: "{{ crawler_image }}:{{ crawler_tag }}"
        state: started
        restart_policy: always
        ports: "{{ crawler_ports }}"

